-- =====================================================================
-- GrowPath AI 통합 데이터베이스 스키마 v3 (Consolidated Schema)
-- 대상: PostgreSQL 15+ / Supabase (pgvector 확장이 활성화된 환경)
-- =====================================================================

-- 0. pgvector 확장 활성화
CREATE EXTENSION IF NOT EXISTS vector;

-- ---------------------------------------------------------------------
-- 1. 스킬 태그 마스터 테이블 (1536차원 OpenAI 임베딩 대응)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS skill_tags (
    skill_id BIGINT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    category VARCHAR(50) DEFAULT 'IT/SW',
    embedding VECTOR(1536),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ---------------------------------------------------------------------
-- 2. 강좌 마스터 테이블 (MS Learn / K-MOOC 등 50건 이상 보장)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS courses (
    course_id VARCHAR(50) PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    category_name VARCHAR(100),
    org_name VARCHAR(100),
    url TEXT NOT NULL,
    is_matchup BOOLEAN DEFAULT FALSE,
    cost NUMERIC(10, 2) DEFAULT 0.00,
    duration_weeks INT DEFAULT 4,
    recruitment_status VARCHAR(50) DEFAULT '상시학습',
    syllabus_summary TEXT,
    platform VARCHAR(50) DEFAULT 'K-MOOC',
    difficulty VARCHAR(30) DEFAULT 'INTERMEDIATE',
    record_source VARCHAR(50) DEFAULT 'REAL_PUBLIC_DATA',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ---------------------------------------------------------------------
-- 3. 공인 자격증 마스터 테이블 (국가기술/국제공인 50건 이상 보장)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS certifications (
    cert_id BIGINT PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    provider VARCHAR(100) NOT NULL,
    test_subjects TEXT,
    career_outlook TEXT,
    exam_type VARCHAR(50) DEFAULT '필기/실기',
    pass_score INT DEFAULT 60,
    record_source VARCHAR(50) DEFAULT 'REAL_PUBLIC_DATA',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ---------------------------------------------------------------------
-- 4. 전문 도서 마스터 테이블 (KDC 004 컴퓨터과학 대출 50건 이상 보장)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS books (
    isbn VARCHAR(30) PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(100),
    publisher VARCHAR(100),
    loan_count INT DEFAULT 0,
    kdc_code VARCHAR(10) DEFAULT '004',
    record_source VARCHAR(50) DEFAULT 'REAL_PUBLIC_DATA',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ---------------------------------------------------------------------
-- 5. 직무 기술 마스터 테이블 (NCS 표준 IT 직무 50건 이상 보장)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS jobs (
    job_id BIGINT PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    ncs_units TEXT,
    record_source VARCHAR(50) DEFAULT 'REAL_PUBLIC_DATA',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ---------------------------------------------------------------------
-- 6. 스킬-엔티티 간 M:N 매핑 관계 테이블군 (ON DELETE CASCADE)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS course_skill_map (
    course_id VARCHAR(50) REFERENCES courses(course_id) ON DELETE CASCADE,
    skill_id BIGINT REFERENCES skill_tags(skill_id) ON DELETE CASCADE,
    PRIMARY KEY (course_id, skill_id)
);

CREATE TABLE IF NOT EXISTS cert_skill_map (
    cert_id BIGINT REFERENCES certifications(cert_id) ON DELETE CASCADE,
    skill_id BIGINT REFERENCES skill_tags(skill_id) ON DELETE CASCADE,
    PRIMARY KEY (cert_id, skill_id)
);

CREATE TABLE IF NOT EXISTS book_skill_map (
    isbn VARCHAR(30) REFERENCES books(isbn) ON DELETE CASCADE,
    skill_id BIGINT REFERENCES skill_tags(skill_id) ON DELETE CASCADE,
    PRIMARY KEY (isbn, skill_id)
);

CREATE TABLE IF NOT EXISTS job_skill_map (
    job_id BIGINT REFERENCES jobs(job_id) ON DELETE CASCADE,
    skill_id BIGINT REFERENCES skill_tags(skill_id) ON DELETE CASCADE,
    PRIMARY KEY (job_id, skill_id)
);

-- ---------------------------------------------------------------------
-- 7. 로드맵 요청 세션 및 에이전트 생성/채택 추적 테이블군
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS roadmap_requests (
    request_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_type VARCHAR(50) DEFAULT 'REAL_USER',
    raw_user_prompt TEXT,
    user_profile JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS agent_generations (
    generation_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    request_id BIGINT REFERENCES roadmap_requests(request_id) ON DELETE CASCADE,
    agent_id VARCHAR(50) NOT NULL,
    status VARCHAR(20) DEFAULT 'SUCCESS',
    provider VARCHAR(50),
    model VARCHAR(50),
    latency_ms INT,
    summary TEXT,
    roadmap_content JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS user_selections (
    selection_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    request_id BIGINT REFERENCES roadmap_requests(request_id) ON DELETE CASCADE,
    chosen_generation_id BIGINT REFERENCES agent_generations(generation_id) ON DELETE CASCADE,
    chosen_agent_id VARCHAR(50) NOT NULL,
    user_type VARCHAR(50) DEFAULT 'REAL_USER',
    selection_reason TEXT,
    selected_at TIMESTAMPTZ DEFAULT NOW()
);

-- ---------------------------------------------------------------------
-- 8. 성능 최적화: pgvector HNSW 코사인 인덱스 생성
-- ---------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_skill_tags_embedding_hnsw
ON skill_tags
USING hnsw (embedding vector_cosine_ops);

-- ---------------------------------------------------------------------
-- 9. 코사인 유사도 기반 스킬 검색 RPC 함수 (Supabase PostgREST 연동)
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION match_skills (
    query_embedding VECTOR(1536),
    match_threshold FLOAT DEFAULT 0.25,
    match_count INT DEFAULT 5
)
RETURNS TABLE (
    skill_id BIGINT,
    name VARCHAR(100),
    category VARCHAR(50),
    similarity FLOAT
)
LANGUAGE sql STABLE
AS $$
    SELECT
        skill_tags.skill_id,
        skill_tags.name,
        skill_tags.category,
        1 - (skill_tags.embedding <=> query_embedding) AS similarity
    FROM skill_tags
    WHERE skill_tags.embedding IS NOT NULL
      AND (1 - (skill_tags.embedding <=> query_embedding)) >= match_threshold
    ORDER BY (skill_tags.embedding <=> query_embedding) ASC
    LIMIT match_count;
$$;